{
"urls":[
//{"url":"","name":"请点击下方线路观看"},
{
"url":"https://agit.ai/XiaoYiChaHang/xxzb/raw/branch/master/ysj.json",
"name":"小易大众接口"
},
{
"url":"https://agit.ai/XiaoYiChaHang/xxzj/raw/branch/master/ysj.json",
"name":"小易自用接口"
},
{
"url":"https://ghproxy.com/https://raw.githubusercontent.com/zhanghong1983/TVBOXZY/main/tvbox.json",
"name":"张弘在线接口"
},
{
"url":"https://agit.ai/Yoursmile7/TVBox/raw/branch/master/XC.json",
"name":"南风在线接口"
},
{
"url":"http://肥猫.love",
"name":"肥猫在线接口"
},
{
"url":"https://tvbox.cainisi.cf",
"name":"菜妮丝的接口"
},
{
"url":"http://饭太硬.ga/x/o.json",
"name":"饭太硬的接口"
},
{
"url":"https://hutool.ml/tang",
"name":"唐三在线接口"
},
{
"url":"http://pandown.pro/tvbox/tvbox.json",
"name":"巧技在线接口"
},
{
"url":"http://home.jundie.top:81/top98.json",
"name":"俊于在线接口"
},
{
"url":"http://drpy.site/js1",
"name":"小雅在线接口"
},
{
"url":"https://agit.ai/66666/mao/raw/branch/master/00/000.m3u8",
"name":"一个分者接口"
},
{
"url":"https://raw.fastgit.org/liu673cn/box/main/m.json",
"name":"老刘备主接口"
},
{
"url":"https://raw.liucn.cc/box/m.json",
"name":"老刘备副接口"
},
{
"url":"https://agit.ai/nbwzlyd/xiaopingguo/raw/branch/master/xiaopingguo/xiaopingguo.json",
"name":"小苹果的接口"
},
{
"url":"https://maoyingshi.cc/tvbox/云星日记/1.m3u8",
"name":"云星日记接口"
},
{
"url":"http://maoyingshi.cc/tvbox/云星日记/bili.json",
"name":"云星哔哩接口"
},
{
"url":"http://maoyingshi.cc/tvbox/云星日记/ali.m3u8",
"name":"云星阿里接口"
},
{
"url":"https://ghproxy.com/https://raw.githubusercontent.com/chengxueli818913/maoTV/main/新建 文本文档8.txt",
"name":"佰欣园的接口"
},
{
"url":"http://52bsj.vip:98/wuai",
"name":"吾爱在线接口"
},
{
"url":"http://js.134584.xyz/json/pp87.json",
"name":"白嫖在线接口"
},
{
"url":"https://raw.iqiq.io/2hacc/TVBox/main/tvbox",
"name":"二哈在线接口"
},
{
"url":"http://52bsj.vip:81/api/v3/file/get/29899/box2.json?sign=3cVyKZQr3lFAwdB3HK-A7h33e0MnmG6lLB9oWlvSNnM%3D%3A0",
"name":"月光宝盒接口"
}
],
"vip": [
{
"url":"",
"name":""
}
]
}